services:

  api:
    build:
      context: ./product-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/samykin_payouts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: "12345678901234567890123456789012"
      APP_SEED_DATA_DIR: seed-data
      APP_USERS_FILE: /tmp/users.txt
      GIGACHAT_TOKEN: ${GIGACHAT_TOKEN:-}
    ports:
      - "8081:8080"
volumes:
  postgres-data:
