spring.application.name=product-api
spring.application.name=product-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/samykin_payouts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.error.include-message=always
spring.jackson.serialization.write-dates-as-timestamps=false
springdoc.swagger-ui.path=/swagger-ui

app.jwt.secret=${APP_JWT_SECRET:change-me-please-change-me-please-change-me}
app.jwt.expiration-minutes=480
app.seed-data-dir=${APP_SEED_DATA_DIR:seed-data}
app.users-file=${APP_USERS_FILE:users.txt}
app.ai.daily-token-limit=20000
app.ai.zone-id=Europe/Samara
app.ai.default-style-name=Деловой
app.ai.default-style-instruction=Пиши кратко, вежливо, официально и понятно для внутреннего документооборота.

spring.ai.gigachat.base-url=${GIGACHAT_BASE_URL:https://gigachat.devices.sberbank.ru/api/v1}
spring.ai.gigachat.credentials=${GIGACHAT_TOKEN:}
